###### admin ######

### get admin
GET http://localhost:3000/admin
###

### get admin com id
GET http://localhost:3000/admin/123
###

### post com envio de dados
POST http://localhost:3000/admin
Content-Type: application/json

{
    "login":"eduardo",
    "senha":"123456"
}
###

### PATCH
PATCH http://localhost:3000/admin/123
###

### PUT
PUT http://localhost:3000/admin/123
###

### DELETE
DELETE http://localhost:3000/admin/123
###


###### User ######

### get user
GET http://localhost:3000/user
###

### get user com id
GET http://localhost:3000/user/123
###

### post com envio de dados
POST http://localhost:3000/user
Content-Type: application/json

{
    "login":"eduardo",
    "senha":"123456"
}
###

### PATCH
PATCH http://localhost:3000/user/123
###

### PUT
PUT http://localhost:3000/user/123
###

### DELETE
DELETE http://localhost:3000/user/123
###